export type TanzaniaLocation = {
  id: string;
  label: string;       // full display name
  shortLabel: string;  // compact name for the selected badge
  city: string;        // region/city for grouping subtitle
  lat: number;
  lng: number;
  category: "airport" | "bus_terminal" | "ferry_port";
  arrivalType: "FLIGHT" | "BUS" | "TRAIN" | "FERRY" | "OTHER";
  iataCode?: string;
};

export const TANZANIA_LOCATIONS: TanzaniaLocation[] = [
  // ── AIRPORTS ──────────────────────────────────────────────────────────────
  {
    id: "JNIA",
    label: "Julius Nyerere International Airport (DAR)",
    shortLabel: "JNIA – Dar es Salaam",
    city: "Dar es Salaam",
    lat: -6.878111,
    lng: 39.202625,
    category: "airport",
    arrivalType: "FLIGHT",
    iataCode: "DAR",
  },
  {
    id: "ZNZ",
    label: "Abeid Amani Karume International Airport (ZNZ)",
    shortLabel: "Karume – Zanzibar",
    city: "Zanzibar (Unguja)",
    lat: -6.222025,
    lng: 39.224886,
    category: "airport",
    arrivalType: "FLIGHT",
    iataCode: "ZNZ",
  },
  {
    id: "JRO",
    label: "Kilimanjaro International Airport (JRO)",
    shortLabel: "KIA – Kilimanjaro",
    city: "Arusha / Moshi",
    lat: -3.42939,
    lng: 37.07454,
    category: "airport",
    arrivalType: "FLIGHT",
    iataCode: "JRO",
  },
  {
    id: "MWZ",
    label: "Mwanza Airport (MWZ)",
    shortLabel: "Mwanza Airport",
    city: "Mwanza",
    lat: -2.44453,
    lng: 32.93274,
    category: "airport",
    arrivalType: "FLIGHT",
    iataCode: "MWZ",
  },
  {
    id: "MBI",
    label: "Songwe Airport (MBI) – Mbeya",
    shortLabel: "Songwe – Mbeya",
    city: "Mbeya",
    lat: -8.91918,
    lng: 33.27349,
    category: "airport",
    arrivalType: "FLIGHT",
    iataCode: "MBI",
  },
  {
    id: "DOD",
    label: "Dodoma Airport (DOD)",
    shortLabel: "Dodoma Airport",
    city: "Dodoma",
    lat: -6.17041,
    lng: 35.75265,
    category: "airport",
    arrivalType: "FLIGHT",
    iataCode: "DOD",
  },
  {
    id: "MYW",
    label: "Mtwara Airport (MYW)",
    shortLabel: "Mtwara Airport",
    city: "Mtwara",
    lat: -10.33910,
    lng: 40.18183,
    category: "airport",
    arrivalType: "FLIGHT",
    iataCode: "MYW",
  },
  {
    id: "TBO",
    label: "Tabora Airport (TBO)",
    shortLabel: "Tabora Airport",
    city: "Tabora",
    lat: -5.07643,
    lng: 32.83330,
    category: "airport",
    arrivalType: "FLIGHT",
    iataCode: "TBO",
  },
  {
    id: "TKQ",
    label: "Kigoma Airport (TKQ)",
    shortLabel: "Kigoma Airport",
    city: "Kigoma",
    lat: -4.88620,
    lng: 29.62900,
    category: "airport",
    arrivalType: "FLIGHT",
    iataCode: "TKQ",
  },
  {
    id: "PMA",
    label: "Pemba Airport (PMA)",
    shortLabel: "Pemba Airport",
    city: "Pemba Island",
    lat: -5.25730,
    lng: 39.81140,
    category: "airport",
    arrivalType: "FLIGHT",
    iataCode: "PMA",
  },
  {
    id: "MFA",
    label: "Mafia Airport (MFA)",
    shortLabel: "Mafia Airport",
    city: "Mafia Island",
    lat: -7.91700,
    lng: 39.66850,
    category: "airport",
    arrivalType: "FLIGHT",
    iataCode: "MFA",
  },
  {
    id: "TGT",
    label: "Tanga Airport (TGT)",
    shortLabel: "Tanga Airport",
    city: "Tanga",
    lat: -5.09240,
    lng: 39.07120,
    category: "airport",
    arrivalType: "FLIGHT",
    iataCode: "TGT",
  },
  {
    id: "LKY",
    label: "Lake Manyara Airport (LKY)",
    shortLabel: "Manyara Airport",
    city: "Manyara",
    lat: -3.37630,
    lng: 35.81820,
    category: "airport",
    arrivalType: "FLIGHT",
    iataCode: "LKY",
  },
  {
    id: "SHY",
    label: "Shinyanga Airport (SHY)",
    shortLabel: "Shinyanga Airport",
    city: "Shinyanga",
    lat: -3.60930,
    lng: 33.50030,
    category: "airport",
    arrivalType: "FLIGHT",
    iataCode: "SHY",
  },
  {
    id: "IRI",
    label: "Iringa Airport (IRI)",
    shortLabel: "Iringa Airport",
    city: "Iringa",
    lat: -7.66880,
    lng: 35.75230,
    category: "airport",
    arrivalType: "FLIGHT",
    iataCode: "IRI",
  },
  {
    id: "MUZ",
    label: "Musoma Airport (MUZ)",
    shortLabel: "Musoma Airport",
    city: "Musoma",
    lat: -1.50300,
    lng: 33.80090,
    category: "airport",
    arrivalType: "FLIGHT",
    iataCode: "MUZ",
  },
  {
    id: "BKZ",
    label: "Bukoba Airport (BKZ)",
    shortLabel: "Bukoba Airport",
    city: "Bukoba",
    lat: -1.33220,
    lng: 31.82120,
    category: "airport",
    arrivalType: "FLIGHT",
    iataCode: "BKZ",
  },

  // ── BUS TERMINALS ─────────────────────────────────────────────────────────
  {
    id: "BUS_UBUNGO",
    label: "Ubungo Bus Terminal",
    shortLabel: "Ubungo – Dar es Salaam",
    city: "Dar es Salaam",
    lat: -6.77239,
    lng: 39.21432,
    category: "bus_terminal",
    arrivalType: "BUS",
  },
  {
    id: "BUS_ARUSHA",
    label: "Arusha Central Bus Stand",
    shortLabel: "Arusha Bus Stand",
    city: "Arusha",
    lat: -3.36670,
    lng: 36.68330,
    category: "bus_terminal",
    arrivalType: "BUS",
  },
  {
    id: "BUS_MOSHI",
    label: "Moshi Bus Stand",
    shortLabel: "Moshi Bus Stand",
    city: "Moshi",
    lat: -3.35000,
    lng: 37.33330,
    category: "bus_terminal",
    arrivalType: "BUS",
  },
  {
    id: "BUS_MWANZA",
    label: "Mwanza Bus Terminal (Buzuruga)",
    shortLabel: "Mwanza Bus Terminal",
    city: "Mwanza",
    lat: -2.51670,
    lng: 32.90000,
    category: "bus_terminal",
    arrivalType: "BUS",
  },
  {
    id: "BUS_DODOMA",
    label: "Dodoma Bus Stand (Jamatini)",
    shortLabel: "Dodoma Bus Stand",
    city: "Dodoma",
    lat: -6.17310,
    lng: 35.73940,
    category: "bus_terminal",
    arrivalType: "BUS",
  },
  {
    id: "BUS_MOROGORO",
    label: "Morogoro Bus Stand",
    shortLabel: "Morogoro Bus Stand",
    city: "Morogoro",
    lat: -6.82030,
    lng: 37.65810,
    category: "bus_terminal",
    arrivalType: "BUS",
  },
  {
    id: "BUS_TANGA",
    label: "Tanga Bus Stand",
    shortLabel: "Tanga Bus Stand",
    city: "Tanga",
    lat: -5.06670,
    lng: 39.10000,
    category: "bus_terminal",
    arrivalType: "BUS",
  },
  {
    id: "BUS_MBEYA",
    label: "Mbeya Bus Stand",
    shortLabel: "Mbeya Bus Stand",
    city: "Mbeya",
    lat: -8.90000,
    lng: 33.45000,
    category: "bus_terminal",
    arrivalType: "BUS",
  },
  {
    id: "BUS_IRINGA",
    label: "Iringa Bus Stand",
    shortLabel: "Iringa Bus Stand",
    city: "Iringa",
    lat: -7.76670,
    lng: 35.70000,
    category: "bus_terminal",
    arrivalType: "BUS",
  },
  {
    id: "BUS_KIGOMA",
    label: "Kigoma Bus Stand",
    shortLabel: "Kigoma Bus Stand",
    city: "Kigoma",
    lat: -4.88330,
    lng: 29.63330,
    category: "bus_terminal",
    arrivalType: "BUS",
  },
  {
    id: "BUS_TABORA",
    label: "Tabora Bus Stand",
    shortLabel: "Tabora Bus Stand",
    city: "Tabora",
    lat: -5.06670,
    lng: 32.80000,
    category: "bus_terminal",
    arrivalType: "BUS",
  },
  {
    id: "BUS_SONGEA",
    label: "Songea Bus Stand",
    shortLabel: "Songea Bus Stand",
    city: "Songea",
    lat: -10.68330,
    lng: 35.65000,
    category: "bus_terminal",
    arrivalType: "BUS",
  },
  {
    id: "BUS_MTWARA",
    label: "Mtwara Bus Stand",
    shortLabel: "Mtwara Bus Stand",
    city: "Mtwara",
    lat: -10.26670,
    lng: 40.18330,
    category: "bus_terminal",
    arrivalType: "BUS",
  },
  {
    id: "BUS_LINDI",
    label: "Lindi Bus Stand",
    shortLabel: "Lindi Bus Stand",
    city: "Lindi",
    lat: -9.95000,
    lng: 39.71670,
    category: "bus_terminal",
    arrivalType: "BUS",
  },
  {
    id: "BUS_MUSOMA",
    label: "Musoma Bus Stand",
    shortLabel: "Musoma Bus Stand",
    city: "Musoma",
    lat: -1.50000,
    lng: 33.80000,
    category: "bus_terminal",
    arrivalType: "BUS",
  },
  {
    id: "BUS_BUKOBA",
    label: "Bukoba Bus Stand",
    shortLabel: "Bukoba Bus Stand",
    city: "Bukoba",
    lat: -1.33330,
    lng: 31.81670,
    category: "bus_terminal",
    arrivalType: "BUS",
  },
  {
    id: "BUS_NJOMBE",
    label: "Njombe Bus Stand",
    shortLabel: "Njombe Bus Stand",
    city: "Njombe",
    lat: -9.33330,
    lng: 34.76670,
    category: "bus_terminal",
    arrivalType: "BUS",
  },
  {
    id: "BUS_SHINYANGA",
    label: "Shinyanga Bus Stand",
    shortLabel: "Shinyanga Bus Stand",
    city: "Shinyanga",
    lat: -3.66000,
    lng: 33.43000,
    category: "bus_terminal",
    arrivalType: "BUS",
  },
  {
    id: "BUS_MWANAKWEREKWE",
    label: "Mwanakwerekwe Bus Terminal",
    shortLabel: "Mwanakwerekwe – Zanzibar",
    city: "Zanzibar (Unguja)",
    lat: -6.17690,
    lng: 39.22750,
    category: "bus_terminal",
    arrivalType: "BUS",
  },

  // ── FERRY PORTS ───────────────────────────────────────────────────────────
  {
    id: "FERRY_KIVUKONI",
    label: "Kivukoni Ferry Terminal – Dar es Salaam",
    shortLabel: "Kivukoni – Dar es Salaam",
    city: "Dar es Salaam",
    lat: -6.81480,
    lng: 39.29180,
    category: "ferry_port",
    arrivalType: "FERRY",
  },
  {
    id: "FERRY_STONETOWN",
    label: "Malindi Port (Stone Town) – Zanzibar",
    shortLabel: "Stone Town Ferry – Zanzibar",
    city: "Zanzibar (Unguja)",
    lat: -6.16220,
    lng: 39.18800,
    category: "ferry_port",
    arrivalType: "FERRY",
  },
  {
    id: "FERRY_MKOANI",
    label: "Mkoani Jetty – Pemba Island",
    shortLabel: "Mkoani – Pemba",
    city: "Pemba Island",
    lat: -5.31670,
    lng: 39.71670,
    category: "ferry_port",
    arrivalType: "FERRY",
  },
  {
    id: "FERRY_CHAKE_CHAKE",
    label: "Chake Chake Port – Pemba Island",
    shortLabel: "Chake Chake – Pemba",
    city: "Pemba Island",
    lat: -5.25000,
    lng: 39.76670,
    category: "ferry_port",
    arrivalType: "FERRY",
  },
  {
    id: "FERRY_MAFIA",
    label: "Mafia Island Jetty",
    shortLabel: "Mafia Jetty",
    city: "Mafia Island",
    lat: -7.90000,
    lng: 39.65000,
    category: "ferry_port",
    arrivalType: "FERRY",
  },
  {
    id: "FERRY_TANGA",
    label: "Tanga Port",
    shortLabel: "Tanga Port",
    city: "Tanga",
    lat: -5.06670,
    lng: 39.10000,
    category: "ferry_port",
    arrivalType: "FERRY",
  },
  {
    id: "FERRY_MWANZA",
    label: "Mwanza Port – Lake Victoria",
    shortLabel: "Mwanza Port",
    city: "Mwanza",
    lat: -2.51670,
    lng: 32.90000,
    category: "ferry_port",
    arrivalType: "FERRY",
  },
  {
    id: "FERRY_BUKOBA",
    label: "Bukoba Port – Lake Victoria",
    shortLabel: "Bukoba Port",
    city: "Bukoba",
    lat: -1.33330,
    lng: 31.81670,
    category: "ferry_port",
    arrivalType: "FERRY",
  },
  {
    id: "FERRY_MUSOMA",
    label: "Musoma Port – Lake Victoria",
    shortLabel: "Musoma Port",
    city: "Musoma",
    lat: -1.50000,
    lng: 33.80000,
    category: "ferry_port",
    arrivalType: "FERRY",
  },
  {
    id: "FERRY_KIGOMA",
    label: "Kigoma Port – Lake Tanganyika",
    shortLabel: "Kigoma Port",
    city: "Kigoma",
    lat: -4.88330,
    lng: 29.63330,
    category: "ferry_port",
    arrivalType: "FERRY",
  },
  {
    id: "FERRY_ITUNGI",
    label: "Itungi Port (Kyela) – Lake Nyasa",
    shortLabel: "Itungi – Kyela",
    city: "Kyela, Mbeya",
    lat: -9.58330,
    lng: 33.98330,
    category: "ferry_port",
    arrivalType: "FERRY",
  },
];

export const LOCATION_CATEGORIES = [
  { key: "airport" as const,      label: "Airports",         icon: "✈" },
  { key: "bus_terminal" as const, label: "Bus Terminals",    icon: "🚌" },
  { key: "ferry_port" as const,   label: "Ferry Ports",      icon: "⛴" },
];
