-- CreateTable: TransportBooking
CREATE TABLE `TransportBooking` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `userId` INT NOT NULL,
  `driverId` INT NULL,
  `propertyId` INT NULL,
  `status` VARCHAR(40) NOT NULL DEFAULT 'PENDING',
  `scheduledDate` DATETIME(3) NOT NULL,
  `pickupTime` DATETIME(3) NULL,
  `dropoffTime` DATETIME(3) NULL,
  `fromRegion` VARCHAR(120) NULL,
  `fromDistrict` VARCHAR(120) NULL,
  `fromWard` VARCHAR(120) NULL,
  `fromAddress` VARCHAR(255) NULL,
  `fromLatitude` DECIMAL(10, 6) NULL,
  `fromLongitude` DECIMAL(10, 6) NULL,
  `toRegion` VARCHAR(120) NULL,
  `toDistrict` VARCHAR(120) NULL,
  `toWard` VARCHAR(120) NULL,
  `toAddress` VARCHAR(255) NULL,
  `toLatitude` DECIMAL(10, 6) NULL,
  `toLongitude` DECIMAL(10, 6) NULL,
  `amount` DECIMAL(12, 2) NULL,
  `currency` VARCHAR(3) NULL DEFAULT 'TZS',
  `numberOfPassengers` INT NULL DEFAULT 1,
  `notes` TEXT NULL,
  `rating` DECIMAL(3, 2) NULL,
  `ratingComment` TEXT NULL,
  `paymentStatus` VARCHAR(40) NULL DEFAULT 'PENDING',
  `paymentMethod` VARCHAR(40) NULL,
  `paymentRef` VARCHAR(80) NULL,
  `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updatedAt` DATETIME(3) NOT NULL,

  PRIMARY KEY (`id`),
  INDEX `TransportBooking_userId_idx` (`userId`),
  INDEX `TransportBooking_driverId_idx` (`driverId`),
  INDEX `TransportBooking_propertyId_idx` (`propertyId`),
  INDEX `TransportBooking_status_idx` (`status`),
  INDEX `TransportBooking_scheduledDate_idx` (`scheduledDate`),
  INDEX `TransportBooking_paymentStatus_idx` (`paymentStatus`),
  CONSTRAINT `TransportBooking_userId_fkey` FOREIGN KEY (`userId`) REFERENCES `User`(`id`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `TransportBooking_driverId_fkey` FOREIGN KEY (`driverId`) REFERENCES `User`(`id`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `TransportBooking_propertyId_fkey` FOREIGN KEY (`propertyId`) REFERENCES `Property`(`id`) ON DELETE SET NULL ON UPDATE CASCADE
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
