-- Seed runtime tourism sites into the lowercase table used by Prisma.
-- Older migrations seeded `TourismSite`; the current model maps to `tourismsite`.

INSERT INTO `tourismsite` (`slug`, `name`, `country`, `description`) VALUES
  ('serengeti-national-park', 'Serengeti National Park', 'Tanzania', NULL),
  ('ngorongoro-crater', 'Ngorongoro Crater', 'Tanzania', NULL),
  ('mount-kilimanjaro', 'Mount Kilimanjaro', 'Tanzania', NULL),
  ('zanzibar', 'Zanzibar (Stone Town + beaches)', 'Tanzania', NULL),
  ('tarangire-national-park', 'Tarangire National Park', 'Tanzania', NULL),
  ('lake-manyara', 'Lake Manyara', 'Tanzania', NULL),
  ('nyerere-national-park', 'Nyerere (Selous)', 'Tanzania', NULL),
  ('ruaha-national-park', 'Ruaha National Park', 'Tanzania', NULL),
  ('mafia-island', 'Mafia Island', 'Tanzania', NULL),
  ('gombe-mahale', 'Gombe / Mahale', 'Tanzania', NULL),
  ('katavi-national-park', 'Katavi National Park', 'Tanzania', NULL),
  ('kitulo-national-park', 'Kitulo National Park', 'Tanzania', NULL),
  ('saanane-island-national-park', 'Saanane Island National Park', 'Tanzania', NULL),
  ('burigi-chato-national-park', 'Burigi-Chato National Park', 'Tanzania', NULL),
  ('rubondo-national-park', 'Rubondo National Park', 'Tanzania', NULL),
  ('gombe-national-park', 'Gombe National Park', 'Tanzania', NULL),
  ('mahale-mountains-national-park', 'Mahale Mountains National Park', 'Tanzania', NULL),
  ('ibanda-kyerwa-national-park', 'Ibanda-Kyerwa National Park', 'Tanzania', NULL),
  ('rumanyika-karagwe-national-park', 'Rumanyika-Karagwe National Park', 'Tanzania', NULL),
  ('ugalla-river-national-park', 'Ugalla River National Park', 'Tanzania', NULL),
  ('arusha-national-park', 'Arusha National Park', 'Tanzania', NULL),
  ('mkomazi-national-park', 'Mkomazi National Park', 'Tanzania', NULL),
  ('kilimanjaro-national-park', 'Kilimanjaro National Park', 'Tanzania', NULL),
  ('saadani-national-park', 'Saadani National Park', 'Tanzania', NULL),
  ('mikumi-national-park', 'Mikumi National Park', 'Tanzania', NULL),
  ('udzungwa-mountains-national-park', 'Udzungwa Mountains National Park', 'Tanzania', NULL),
  ('maasai-mara', 'Maasai Mara', 'Kenya', NULL),
  ('amboseli-national-park', 'Amboseli National Park', 'Kenya', NULL),
  ('tsavo', 'Tsavo (East & West)', 'Kenya', NULL),
  ('diani-beach', 'Diani Beach', 'Kenya', NULL),
  ('nairobi-national-park', 'Nairobi (city + Nairobi National Park)', 'Kenya', NULL),
  ('lake-nakuru', 'Lake Nakuru', 'Kenya', NULL),
  ('samburu', 'Samburu', 'Kenya', NULL),
  ('mount-kenya', 'Mount Kenya', 'Kenya', NULL),
  ('lamu', 'Lamu', 'Kenya', NULL),
  ('hells-gate', 'Hell''s Gate', 'Kenya', NULL),
  ('bwindi-impenetrable', 'Bwindi Impenetrable (Gorilla trekking)', 'Uganda', NULL),
  ('queen-elizabeth-national-park', 'Queen Elizabeth National Park', 'Uganda', NULL)
ON DUPLICATE KEY UPDATE
  `name` = VALUES(`name`),
  `country` = VALUES(`country`),
  `description` = VALUES(`description`);
