export const AVAILABILITY_BLOCKING_BOOKING_STATUSES = [
  "CONFIRMED",
  "PENDING_CHECKIN",
  "CHECKED_IN",
] as const;

export const REAL_BOOKING_STATUSES = [
  ...AVAILABILITY_BLOCKING_BOOKING_STATUSES,
  "CHECKED_OUT",
] as const;
