"use client";
import { useEffect, useState, useMemo } from "react";
import { Bell, Truck, Search, AlertCircle, Info, AlertTriangle, Megaphone, Plus, X, Shield, FileWarning, Calendar, Car, Bike, CarTaxiFront, Target, CheckCircle, Clock, Filter, RefreshCw, BarChart3, TrendingUp, SlidersHorizontal, CalendarDays, Tag, XCircle, ChevronDown, ChevronUp } from "lucide-react";
import axios from "axios";

const api = axios.create({ baseURL: "" });
function authify() {
  const t = typeof window !== "undefined" ? localStorage.getItem("token") : null;
  if (t) api.defaults.headers.common["Authorization"] = `Bearer ${t}`;
}

type Driver = {
  id: number;
  name: string;
  email: string;
  vehicleType?: string;
};

type ReminderData = {
  driver: Driver;
  total: number;
  page: number;
  pageSize: number;
  items: Array<{
    id: string;
    type: "INFO" | "WARNING" | "ALERT" | "PROMOTION" | "POLICY_VIOLATION" | "SAFETY" | "LICENSE_EXPIRY" | "INSURANCE_EXPIRY";
    message: string;
    action: string | null;
    actionLink: string | null;
    expiresAt: string | null;
    isRead: boolean;
    createdAt: string;
  }>;
};

type ReminderType = "POLICY_VIOLATION" | "SAFETY" | "LICENSE_EXPIRY" | "INSURANCE_EXPIRY" | "WARNING" | "INFO" | "ALERT";

const REMINDER_TYPES: Array<{ value: ReminderType; label: string; icon: any; description: string; color: string }> = [
  { value: "POLICY_VIOLATION", label: "Policy Violation", icon: FileWarning, description: "Driver violated company policy", color: "bg-red-100 text-red-700 border-red-200" },
  { value: "SAFETY", label: "Safety Measure", icon: Shield, description: "Safety reminder (e.g., helmet for Motorcycle)", color: "bg-amber-100 text-amber-700 border-amber-200" },
  { value: "LICENSE_EXPIRY", label: "License Expiration", icon: Calendar, description: "Driver license is expiring soon", color: "bg-orange-100 text-orange-700 border-orange-200" },
  { value: "INSURANCE_EXPIRY", label: "Insurance Expiration", icon: Calendar, description: "Insurance is expiring soon", color: "bg-purple-100 text-purple-700 border-purple-200" },
  { value: "WARNING", label: "Warning", icon: AlertTriangle, description: "General warning reminder", color: "bg-yellow-100 text-yellow-700 border-yellow-200" },
  { value: "INFO", label: "Information", icon: Info, description: "General information reminder", color: "bg-blue-100 text-blue-700 border-blue-200" },
  { value: "ALERT", label: "Alert", icon: AlertCircle, description: "Urgent alert reminder", color: "bg-red-100 text-red-700 border-red-200" },
];

const getReminderIcon = (type: string) => {
  const reminderType = REMINDER_TYPES.find(r => r.value === type);
  return reminderType?.icon || Info;
};

const getReminderColor = (type: string) => {
  const reminderType = REMINDER_TYPES.find(r => r.value === type);
  return reminderType?.color || "bg-gray-100 text-gray-700 border-gray-200";
};

export default function AdminDriversRemindersPage() {
  const [drivers, setDrivers] = useState<Driver[]>([]);
  const [selectedDriver, setSelectedDriver] = useState<number | null>(null);
  const [reminderData, setReminderData] = useState<ReminderData | null>(null);
  const [loading, setLoading] = useState(true);
  const [search, setSearch] = useState("");
  const [showCreateModal, setShowCreateModal] = useState(false);
  const [creating, setCreating] = useState(false);
  const [typeFilter, setTypeFilter] = useState<ReminderType | "ALL">("ALL");
  const [statusFilter, setStatusFilter] = useState<"ALL" | "UNREAD" | "READ" | "EXPIRED" | "ACTIVE">("ALL");
  const [expiringDocuments, setExpiringDocuments] = useState<Array<{ driver: Driver; expiringDocuments: Array<{ type: string; expiryDate: string; daysLeft: number }> }>>([]);
  const [loadingExpiring, setLoadingExpiring] = useState(false);
  const [autoCreating, setAutoCreating] = useState(false);
  
  // Advanced filters
  const [showAdvancedFilters, setShowAdvancedFilters] = useState(false);
  const [selectedTypes, setSelectedTypes] = useState<Set<ReminderType>>(new Set());
  const [selectedStatuses, setSelectedStatuses] = useState<Set<"UNREAD" | "READ" | "EXPIRED" | "ACTIVE">>(new Set());
  const [dateRange, setDateRange] = useState<{ start: string; end: string }>({ start: "", end: "" });
  const [autoGeneratedFilter, setAutoGeneratedFilter] = useState<"ALL" | "AUTO" | "MANUAL">("ALL");
  const [priorityFilter, setPriorityFilter] = useState<"ALL" | "HIGH" | "MEDIUM" | "LOW">("ALL");
  const [activeFilters, setActiveFilters] = useState<Array<{ key: string; label: string; value: string }>>([]);
  const [reminderSearch, setReminderSearch] = useState("");
  const [sortBy, setSortBy] = useState<"NEWEST" | "OLDEST" | "PRIORITY" | "EXPIRY">("NEWEST");
  
  // Create reminder form state
  const [reminderType, setReminderType] = useState<ReminderType>("INFO");
  const [reminderMessage, setReminderMessage] = useState("");
  const [reminderAction, setReminderAction] = useState("");
  const [reminderActionLink, setReminderActionLink] = useState("");
  const [reminderExpiresAt, setReminderExpiresAt] = useState("");
  const [reminderGoal, setReminderGoal] = useState("");

  useEffect(() => {
    authify();
    loadDrivers();
    loadExpiringDocuments();
  }, []);

  async function loadExpiringDocuments() {
    setLoadingExpiring(true);
    try {
      const r = await api.get<{ drivers: Array<{ driver: Driver; expiringDocuments: Array<{ type: string; expiryDate: string; daysLeft: number }> }> }>("/admin/drivers/expiring-documents");
      setExpiringDocuments(r.data?.drivers ?? []);
    } catch (err) {
      console.error("Failed to load expiring documents", err);
      setExpiringDocuments([]);
    } finally {
      setLoadingExpiring(false);
    }
  }

  async function autoCreateReminders() {
    setAutoCreating(true);
    try {
      const r = await api.post<{ created: number; reminders: any[]; stats: { license: number; insurance: number; rating: number; safety: number; security: number; goals: number; earnings: number } }>("/admin/drivers/auto-create-reminders");
      const stats = r.data.stats || {};
      const message = `Successfully created ${r.data.created} automatic reminders:\n` +
        `• License Expiry: ${stats.license}\n` +
        `• Insurance Expiry: ${stats.insurance}\n` +
        `• Rating-based: ${stats.rating}\n` +
        `• Safety: ${stats.safety}\n` +
        `• Security: ${stats.security}\n` +
        `• Goals: ${stats.goals}\n` +
        `• Earnings: ${stats.earnings}`;
      alert(message);
      await loadExpiringDocuments();
      if (selectedDriver) {
        await loadDriverReminders(selectedDriver);
      }
    } catch (err) {
      console.error("Failed to auto-create reminders", err);
      alert("Failed to auto-create reminders. Please try again.");
    } finally {
      setAutoCreating(false);
    }
  }

  async function loadDrivers() {
    setLoading(true);
    try {
      const r = await api.get<{ items: Driver[]; total: number }>("/admin/drivers", { params: { page: 1, pageSize: 100 } });
      setDrivers(r.data?.items ?? []);
    } catch (err) {
      console.error("Failed to load drivers", err);
      setDrivers([]);
    } finally {
      setLoading(false);
    }
  }

  async function loadDriverReminders(driverId: number) {
    try {
      const r = await api.get<ReminderData>(`/admin/drivers/${driverId}/reminders`, { params: { page: 1, pageSize: 50 } });
      if (r.data) {
        setReminderData(r.data);
      } else {
        const driver = drivers.find(d => d.id === driverId);
        if (driver) {
          setReminderData({
            driver,
            total: 0,
            page: 1,
            pageSize: 50,
            items: [],
          });
        }
      }
      setSelectedDriver(driverId);
    } catch (err) {
      console.error("Failed to load driver reminders", err);
      const driver = drivers.find(d => d.id === driverId);
      if (driver) {
        setReminderData({
          driver,
          total: 0,
          page: 1,
          pageSize: 50,
          items: [],
        });
      }
      setSelectedDriver(driverId);
    }
  }

  async function createReminder() {
    if (!selectedDriver || !reminderMessage.trim()) return;

    setCreating(true);
    try {
      const payload: any = {
        driverId: selectedDriver,
        type: reminderType,
        message: reminderMessage.trim(),
        action: reminderAction.trim() || null,
        actionLink: reminderActionLink.trim() || null,
        expiresAt: reminderExpiresAt || null,
      };

      // Add goal to meta if provided
      if (reminderGoal.trim()) {
        payload.meta = { goal: reminderGoal.trim() };
      }

      await api.post("/api/driver/reminders", payload);
      
      // Reset form
      setReminderMessage("");
      setReminderAction("");
      setReminderActionLink("");
      setReminderExpiresAt("");
      setReminderGoal("");
      setReminderType("INFO");
      setShowCreateModal(false);
      
      // Reload reminders
      if (selectedDriver) {
        await loadDriverReminders(selectedDriver);
      }
    } catch (err) {
      console.error("Failed to create reminder", err);
      alert("Failed to create reminder. Please try again.");
    } finally {
      setCreating(false);
    }
  }

  // Auto-fill message based on reminder type
  useEffect(() => {
    if (reminderType === "SAFETY" && selectedDriver) {
      const driver = drivers.find(d => d.id === selectedDriver);
      if (driver?.vehicleType === "MotorCycle") {
        setReminderMessage("Please ensure you always wear a helmet while driving. Safety is our top priority.");
      } else {
        setReminderMessage("Please follow all safety measures while driving. Safety is our top priority.");
      }
    } else if (reminderType === "LICENSE_EXPIRY") {
      setReminderMessage("Your driver's license is expiring soon. Please renew it before the expiration date to avoid service interruption.");
    } else if (reminderType === "INSURANCE_EXPIRY") {
      setReminderMessage("Your vehicle insurance is expiring soon. Please renew it before the expiration date to maintain coverage.");
    } else if (reminderType === "POLICY_VIOLATION") {
      setReminderMessage("");
    }
  }, [reminderType, selectedDriver, drivers]);

  const filteredDrivers = drivers.filter(
    (d) => d.name.toLowerCase().includes(search.toLowerCase()) || d.email.toLowerCase().includes(search.toLowerCase())
  );

  const selectedDriverData = drivers.find(d => d.id === selectedDriver);

  // Advanced filtering logic
  const filteredReminders = useMemo(() => {
    if (!reminderData) return [];
    
    let filtered = reminderData.items;

    // Advanced type filtering (multi-select)
    if (selectedTypes.size > 0) {
      filtered = filtered.filter(r => selectedTypes.has(r.type as ReminderType));
    } else if (typeFilter !== "ALL") {
      filtered = filtered.filter(r => r.type === typeFilter);
    }

    // Advanced status filtering (multi-select)
    if (selectedStatuses.size > 0) {
      filtered = filtered.filter(r => {
        if (selectedStatuses.has("UNREAD") && !r.isRead) return true;
        if (selectedStatuses.has("READ") && r.isRead) return true;
        if (selectedStatuses.has("EXPIRED") && r.expiresAt && new Date(r.expiresAt) < new Date()) return true;
        if (selectedStatuses.has("ACTIVE") && (!r.expiresAt || new Date(r.expiresAt) > new Date())) return true;
        return false;
      });
    } else if (statusFilter !== "ALL") {
      if (statusFilter === "UNREAD") {
        filtered = filtered.filter(r => !r.isRead);
      } else if (statusFilter === "READ") {
        filtered = filtered.filter(r => r.isRead);
      } else if (statusFilter === "EXPIRED") {
        filtered = filtered.filter(r => r.expiresAt && new Date(r.expiresAt) < new Date());
      } else if (statusFilter === "ACTIVE") {
        filtered = filtered.filter(r => !r.expiresAt || new Date(r.expiresAt) > new Date());
      }
    }

    // Date range filter
    if (dateRange.start) {
      const startDate = new Date(dateRange.start);
      startDate.setHours(0, 0, 0, 0);
      filtered = filtered.filter(r => new Date(r.createdAt) >= startDate);
    }
    if (dateRange.end) {
      const endDate = new Date(dateRange.end);
      endDate.setHours(23, 59, 59, 999);
      filtered = filtered.filter(r => new Date(r.createdAt) <= endDate);
    }

    // Auto-generated filter
    if (autoGeneratedFilter !== "ALL") {
      filtered = filtered.filter(r => {
        const meta = (r as any).meta || {};
        const isAuto = meta.autoGenerated === true;
        return autoGeneratedFilter === "AUTO" ? isAuto : !isAuto;
      });
    }

    // Priority filter (based on type)
    if (priorityFilter !== "ALL") {
      filtered = filtered.filter(r => {
        if (priorityFilter === "HIGH") {
          return r.type === "ALERT" || r.type === "POLICY_VIOLATION";
        } else if (priorityFilter === "MEDIUM") {
          return r.type === "WARNING" || r.type === "LICENSE_EXPIRY" || r.type === "INSURANCE_EXPIRY";
        } else if (priorityFilter === "LOW") {
          return r.type === "INFO" || r.type === "SAFETY";
        }
        return true;
      });
    }

    // Search filter
    if (reminderSearch.trim()) {
      const searchLower = reminderSearch.toLowerCase();
      filtered = filtered.filter(r => 
        r.message.toLowerCase().includes(searchLower) ||
        r.type.toLowerCase().includes(searchLower) ||
        (r.action && r.action.toLowerCase().includes(searchLower))
      );
    }

    // Sorting
    filtered.sort((a, b) => {
      if (sortBy === "NEWEST") {
        return new Date(b.createdAt).getTime() - new Date(a.createdAt).getTime();
      } else if (sortBy === "OLDEST") {
        return new Date(a.createdAt).getTime() - new Date(b.createdAt).getTime();
      } else if (sortBy === "PRIORITY") {
        const priorityOrder: Record<string, number> = {
          "ALERT": 1,
          "POLICY_VIOLATION": 2,
          "WARNING": 3,
          "LICENSE_EXPIRY": 4,
          "INSURANCE_EXPIRY": 5,
          "SAFETY": 6,
          "INFO": 7,
        };
        return (priorityOrder[a.type] || 99) - (priorityOrder[b.type] || 99);
      } else if (sortBy === "EXPIRY") {
        if (!a.expiresAt && !b.expiresAt) return 0;
        if (!a.expiresAt) return 1;
        if (!b.expiresAt) return -1;
        return new Date(a.expiresAt).getTime() - new Date(b.expiresAt).getTime();
      }
      return 0;
    });

    return filtered;
  }, [reminderData, typeFilter, statusFilter, selectedTypes, selectedStatuses, dateRange, autoGeneratedFilter, priorityFilter, reminderSearch, sortBy]);

  // Update active filters display
  useEffect(() => {
    const active: Array<{ key: string; label: string; value: string }> = [];
    
    if (selectedTypes.size > 0) {
      selectedTypes.forEach(type => {
        const typeLabel = REMINDER_TYPES.find(t => t.value === type)?.label || type;
        active.push({ key: `type-${type}`, label: "Type", value: typeLabel });
      });
    }
    
    if (selectedStatuses.size > 0) {
      selectedStatuses.forEach(status => {
        active.push({ key: `status-${status}`, label: "Status", value: status });
      });
    }
    
    if (dateRange.start) {
      active.push({ key: "date-start", label: "From", value: new Date(dateRange.start).toLocaleDateString() });
    }
    
    if (dateRange.end) {
      active.push({ key: "date-end", label: "To", value: new Date(dateRange.end).toLocaleDateString() });
    }
    
    if (autoGeneratedFilter !== "ALL") {
      active.push({ key: "auto", label: "Source", value: autoGeneratedFilter === "AUTO" ? "Auto-generated" : "Manual" });
    }
    
    if (priorityFilter !== "ALL") {
      active.push({ key: "priority", label: "Priority", value: priorityFilter });
    }
    
    setActiveFilters(active);
  }, [selectedTypes, selectedStatuses, dateRange, autoGeneratedFilter, priorityFilter]);

  // Filter presets
  const filterPresets = [
    {
      name: "Urgent Reminders",
      apply: () => {
        setSelectedTypes(new Set(["ALERT", "POLICY_VIOLATION"]));
        setSelectedStatuses(new Set(["UNREAD"]));
        setPriorityFilter("HIGH");
        setTypeFilter("ALL");
        setStatusFilter("ALL");
      },
    },
    {
      name: "Expiring Documents",
      apply: () => {
        setSelectedTypes(new Set(["LICENSE_EXPIRY", "INSURANCE_EXPIRY"]));
        setSelectedStatuses(new Set(["ACTIVE", "UNREAD"]));
        setPriorityFilter("MEDIUM");
        setTypeFilter("ALL");
        setStatusFilter("ALL");
      },
    },
    {
      name: "Auto-Generated",
      apply: () => {
        setAutoGeneratedFilter("AUTO");
        setSelectedTypes(new Set());
        setSelectedStatuses(new Set());
        setTypeFilter("ALL");
        setStatusFilter("ALL");
      },
    },
    {
      name: "Unread Only",
      apply: () => {
        setSelectedStatuses(new Set(["UNREAD"]));
        setSelectedTypes(new Set());
        setTypeFilter("ALL");
        setStatusFilter("ALL");
      },
    },
    {
      name: "This Week",
      apply: () => {
        const today = new Date();
        const weekAgo = new Date(today);
        weekAgo.setDate(weekAgo.getDate() - 7);
        setDateRange({
          start: weekAgo.toISOString().split('T')[0],
          end: today.toISOString().split('T')[0],
        });
      },
    },
  ];

  // Clear all filters
  const clearAllFilters = () => {
    setSelectedTypes(new Set());
    setSelectedStatuses(new Set());
    setDateRange({ start: "", end: "" });
    setAutoGeneratedFilter("ALL");
    setPriorityFilter("ALL");
    setTypeFilter("ALL");
    setStatusFilter("ALL");
    setReminderSearch("");
  };

  // Remove specific filter
  const removeFilter = (key: string) => {
    if (key.startsWith("type-")) {
      const type = key.replace("type-", "") as ReminderType;
      setSelectedTypes(prev => {
        const newSet = new Set(prev);
        newSet.delete(type);
        return newSet;
      });
    } else if (key.startsWith("status-")) {
      const status = key.replace("status-", "") as "UNREAD" | "READ" | "EXPIRED" | "ACTIVE";
      setSelectedStatuses(prev => {
        const newSet = new Set(prev);
        newSet.delete(status);
        return newSet;
      });
    } else if (key === "date-start") {
      setDateRange(prev => ({ ...prev, start: "" }));
    } else if (key === "date-end") {
      setDateRange(prev => ({ ...prev, end: "" }));
    } else if (key === "auto") {
      setAutoGeneratedFilter("ALL");
    } else if (key === "priority") {
      setPriorityFilter("ALL");
    }
  };

  // Calculate statistics
  const reminderStats = useMemo(() => {
    if (!reminderData) return { total: 0, unread: 0, expired: 0, byType: {} };
    
    return {
      total: reminderData.items.length,
      unread: reminderData.items.filter(r => !r.isRead).length,
      expired: reminderData.items.filter(r => r.expiresAt && new Date(r.expiresAt) < new Date()).length,
      byType: reminderData.items.reduce((acc: any, r) => {
        acc[r.type] = (acc[r.type] || 0) + 1;
        return acc;
      }, {}),
    };
  }, [reminderData]);

  return (
    <div className="space-y-6">
      <div className="bg-white rounded-lg border border-gray-200 p-6 shadow-sm">
        <div className="flex flex-col items-center justify-center text-center mb-4">
          <div className="h-12 w-12 rounded-full bg-gradient-to-br from-indigo-50 to-indigo-100 flex items-center justify-center mb-3">
            <Bell className="h-6 w-6 text-indigo-600" />
          </div>
          <h1 className="text-2xl font-bold text-gray-900">Driver Reminders</h1>
          <p className="text-sm text-gray-500 mt-1">View and manage driver reminders and notifications</p>
        </div>
        
        {/* Expiring Documents Alert */}
        {expiringDocuments.length > 0 && (
          <div className="mt-4 p-4 bg-amber-50 border-2 border-amber-200 rounded-lg">
            <div className="flex items-center justify-between">
              <div className="flex items-center gap-3">
                <AlertTriangle className="h-5 w-5 text-amber-600" />
                <div>
                  <p className="font-semibold text-amber-900">
                    {expiringDocuments.length} driver{expiringDocuments.length > 1 ? 's' : ''} with expiring documents
                  </p>
                  <p className="text-sm text-amber-700">
                    {expiringDocuments.reduce((sum, d) => sum + d.expiringDocuments.length, 0)} document{expiringDocuments.reduce((sum, d) => sum + d.expiringDocuments.length, 0) > 1 ? 's' : ''} expiring (License: 100 days, Insurance: 90 days)
                  </p>
                </div>
              </div>
              <button
                onClick={autoCreateReminders}
                disabled={autoCreating}
                className="px-4 py-2 bg-amber-600 text-white rounded-lg hover:bg-amber-700 transition-all disabled:opacity-50 disabled:cursor-not-allowed flex items-center gap-2"
              >
                <RefreshCw className={`h-4 w-4 ${autoCreating ? "animate-spin" : ""}`} />
                {autoCreating ? "Creating..." : "Auto-Create Reminders"}
              </button>
            </div>
          </div>
        )}
      </div>

      <div className="grid grid-cols-1 lg:grid-cols-3 gap-6 w-full">
        <div className="lg:col-span-1 w-full min-w-0 max-w-full">
          <div className="bg-white rounded-lg border border-gray-200 shadow-sm overflow-hidden w-full">
            <div className="p-3 border-b border-gray-200 w-full" style={{ boxSizing: 'border-box', maxWidth: '100%', overflow: 'hidden' }}>
              <div className="relative w-full" style={{ maxWidth: '100%', boxSizing: 'border-box' }}>
                <Search className="absolute left-2.5 top-1/2 transform -translate-y-1/2 h-4 w-4 text-gray-400 pointer-events-none z-10" />
                <input
                  type="text"
                  placeholder="Search drivers..."
                  value={search}
                  onChange={(e) => setSearch(e.target.value)}
                  className="w-full pl-9 pr-3 py-2 border border-gray-300 rounded-lg text-sm focus:ring-2 focus:ring-emerald-500 focus:border-emerald-500 outline-none"
                  style={{ 
                    boxSizing: 'border-box', 
                    maxWidth: '100%',
                    width: '100%',
                    WebkitBoxSizing: 'border-box',
                    MozBoxSizing: 'border-box'
                  }}
                />
              </div>
            </div>
            <div className="divide-y divide-gray-200 max-h-[600px] overflow-y-auto">
              {filteredDrivers.map((driver) => (
                <div
                  key={driver.id}
                  onClick={() => loadDriverReminders(driver.id)}
                  className={`p-4 hover:bg-gray-50 cursor-pointer transition-colors ${
                    selectedDriver === driver.id ? "bg-emerald-50 border-l-4 border-emerald-600" : ""
                  }`}
                >
                  <div className="flex items-center gap-3">
                    <div className="h-10 w-10 rounded-full bg-emerald-100 flex items-center justify-center">
                      {driver.vehicleType === "Car" ? (
                        <Car className="h-5 w-5 text-emerald-600" />
                      ) : driver.vehicleType === "MotorCycle" ? (
                        <Bike className="h-5 w-5 text-emerald-600" />
                      ) : driver.vehicleType === "Tuktuk" ? (
                        <CarTaxiFront className="h-5 w-5 text-emerald-600" />
                      ) : (
                        <Truck className="h-5 w-5 text-emerald-600" />
                      )}
                    </div>
                    <div>
                      <p className="font-medium text-gray-900">{driver.name}</p>
                      <p className="text-xs text-gray-500">{driver.email}</p>
                    </div>
                  </div>
                </div>
              ))}
            </div>
          </div>
        </div>

        <div className="lg:col-span-2 min-w-0" style={{ boxSizing: 'border-box', maxWidth: '100%', overflow: 'hidden' }}>
          {reminderData ? (
            <div className="space-y-6 min-w-0" style={{ boxSizing: 'border-box', maxWidth: '100%', overflow: 'hidden' }}>
              <div className="bg-white rounded-lg border border-gray-200 shadow-sm p-4 md:p-6 overflow-hidden" style={{ boxSizing: 'border-box', maxWidth: '100%', width: '100%' }}>
                <div className="flex flex-col sm:flex-row items-start sm:items-center justify-between gap-3 mb-6 min-w-0" style={{ boxSizing: 'border-box', maxWidth: '100%' }}>
                  <div className="min-w-0" style={{ boxSizing: 'border-box', maxWidth: '100%' }}>
                    <h2 className="text-xl font-bold text-gray-900 mb-2 truncate">{reminderData.driver.name}</h2>
                    <p className="text-sm text-gray-500 truncate">{reminderData.driver.email}</p>
                  </div>
                  <button
                    onClick={() => setShowCreateModal(true)}
                    className="px-3 md:px-4 py-2 bg-emerald-600 text-white rounded-lg hover:bg-emerald-700 transition-all flex items-center gap-2 whitespace-nowrap flex-shrink-0"
                    style={{ boxSizing: 'border-box' }}
                  >
                    <Plus className="h-4 w-4" />
                    <span className="hidden sm:inline">Create Reminder</span>
                    <span className="sm:hidden">Create</span>
                  </button>
                </div>
                
                {/* Statistics Cards */}
                <div className="grid grid-cols-2 md:grid-cols-4 gap-3 md:gap-4 mb-6 min-w-0" style={{ boxSizing: 'border-box', maxWidth: '100%' }}>
                  <div className="p-3 md:p-4 bg-indigo-50 rounded-lg border border-indigo-200 min-w-0" style={{ boxSizing: 'border-box', maxWidth: '100%' }}>
                    <p className="text-xs md:text-sm font-medium text-gray-700 mb-1 truncate">Total</p>
                    <p className="text-xl md:text-2xl font-bold text-indigo-600 truncate">{reminderStats.total}</p>
                  </div>
                  <div className="p-3 md:p-4 bg-amber-50 rounded-lg border border-amber-200 min-w-0" style={{ boxSizing: 'border-box', maxWidth: '100%' }}>
                    <p className="text-xs md:text-sm font-medium text-gray-700 mb-1 truncate">Unread</p>
                    <p className="text-xl md:text-2xl font-bold text-amber-600 truncate">{reminderStats.unread}</p>
                  </div>
                  <div className="p-3 md:p-4 bg-red-50 rounded-lg border border-red-200 min-w-0" style={{ boxSizing: 'border-box', maxWidth: '100%' }}>
                    <p className="text-xs md:text-sm font-medium text-gray-700 mb-1 truncate">Expired</p>
                    <p className="text-xl md:text-2xl font-bold text-red-600 truncate">{reminderStats.expired}</p>
                  </div>
                  <div className="p-3 md:p-4 bg-emerald-50 rounded-lg border border-emerald-200 min-w-0" style={{ boxSizing: 'border-box', maxWidth: '100%' }}>
                    <p className="text-xs md:text-sm font-medium text-gray-700 mb-1 truncate">Active</p>
                    <p className="text-xl md:text-2xl font-bold text-emerald-600 truncate">
                      {reminderData.items.filter((r) => !r.expiresAt || new Date(r.expiresAt) > new Date()).length}
                    </p>
                  </div>
                </div>

                {/* Quick Filters Only */}
                <div className="mb-6 min-w-0" style={{ boxSizing: 'border-box', maxWidth: '100%', overflow: 'hidden' }}>
                  <div className="flex flex-wrap items-center gap-2" style={{ boxSizing: 'border-box', maxWidth: '100%' }}>
                    <span className="text-sm text-gray-600 font-medium whitespace-nowrap">Quick Filters:</span>
                    {filterPresets.map((preset, idx) => (
                      <button
                        key={idx}
                        onClick={preset.apply}
                        className="px-4 py-2 text-sm font-medium bg-emerald-50 text-emerald-700 border border-emerald-200 rounded-full hover:bg-emerald-100 transition-all whitespace-nowrap"
                        style={{ boxSizing: 'border-box' }}
                      >
                        {preset.name}
                      </button>
                    ))}
                  </div>
                </div>

                <div className="min-w-0" style={{ boxSizing: 'border-box', maxWidth: '100%', overflow: 'hidden' }}>
                  <div className="flex flex-col sm:flex-row items-start sm:items-center justify-between gap-3 mb-4 min-w-0" style={{ boxSizing: 'border-box', maxWidth: '100%' }}>
                    <h3 className="text-lg font-semibold text-gray-900 whitespace-nowrap">Reminder List</h3>
                    <div className="flex items-center gap-2 w-full sm:w-auto min-w-0" style={{ boxSizing: 'border-box', maxWidth: '100%' }}>
                      <select
                        value={sortBy}
                        onChange={(e) => setSortBy(e.target.value as any)}
                        className="flex-1 sm:flex-none px-3 py-1.5 text-sm border-2 border-gray-300 rounded-lg focus:outline-none focus:border-emerald-500 bg-white min-w-0"
                        style={{ boxSizing: 'border-box', maxWidth: '100%' }}
                      >
                        <option value="NEWEST">Newest First</option>
                        <option value="OLDEST">Oldest First</option>
                        <option value="PRIORITY">Priority</option>
                        <option value="EXPIRY">Expiry Date</option>
                      </select>
                      <button
                        onClick={() => {
                          if (selectedDriver) loadDriverReminders(selectedDriver);
                          loadExpiringDocuments();
                        }}
                        className="px-3 py-1.5 text-sm bg-gray-100 text-gray-700 rounded-lg hover:bg-gray-200 transition-all flex items-center gap-2 whitespace-nowrap flex-shrink-0"
                        style={{ boxSizing: 'border-box' }}
                      >
                        <RefreshCw className="h-4 w-4" />
                        <span className="hidden sm:inline">Refresh</span>
                      </button>
                    </div>
                  </div>

                  {/* Search Bar & Results Count */}
                  <div className="mb-4 space-y-2 min-w-0" style={{ boxSizing: 'border-box', maxWidth: '100%', overflow: 'hidden' }}>
                    <div className="relative min-w-0" style={{ boxSizing: 'border-box', maxWidth: '100%' }}>
                      <Search className="absolute left-3 top-1/2 transform -translate-y-1/2 h-4 w-4 text-gray-400 pointer-events-none z-10" />
                      <input
                        type="text"
                        placeholder="Search reminders by message, type, or action..."
                        value={reminderSearch}
                        onChange={(e) => setReminderSearch(e.target.value)}
                        className="w-full pl-10 pr-10 py-2.5 border-2 border-gray-300 rounded-lg focus:outline-none focus:border-emerald-500 focus:ring-2 focus:ring-emerald-200 transition-all"
                        style={{ boxSizing: 'border-box', maxWidth: '100%' }}
                      />
                      {reminderSearch && (
                        <button
                          onClick={() => setReminderSearch("")}
                          className="absolute right-3 top-1/2 transform -translate-y-1/2 text-gray-400 hover:text-gray-600 transition-colors z-10"
                        >
                          <X className="h-4 w-4" />
                        </button>
                      )}
                    </div>
                    <div className="flex flex-col sm:flex-row items-start sm:items-center justify-between gap-2 text-sm min-w-0" style={{ boxSizing: 'border-box', maxWidth: '100%' }}>
                      <span className="text-gray-600 text-xs sm:text-sm">
                        Showing <span className="font-semibold text-gray-900">{filteredReminders.length}</span> of <span className="font-semibold text-gray-900">{reminderData.items.length}</span> reminders
                      </span>
                      {(activeFilters.length > 0 || reminderSearch) && (
                        <button
                          onClick={clearAllFilters}
                          className="text-emerald-600 hover:text-emerald-700 font-medium flex items-center gap-1 text-xs sm:text-sm whitespace-nowrap"
                        >
                          <XCircle className="h-4 w-4" />
                          Clear Filters
                        </button>
                      )}
                    </div>
                  </div>
                  <div className="space-y-3 max-h-[500px] overflow-y-auto pr-2" style={{ boxSizing: 'border-box' }}>
                    {filteredReminders.length > 0 ? (
                      filteredReminders.map((reminder) => {
                        const Icon = getReminderIcon(reminder.type);
                        return (
                          <div
                            key={reminder.id}
                            className={`border rounded-lg p-4 ${getReminderColor(reminder.type)} ${!reminder.isRead ? "ring-2 ring-offset-2" : ""} break-words`}
                            style={{ boxSizing: 'border-box', maxWidth: '100%', wordWrap: 'break-word' }}
                          >
                            <div className="flex items-start gap-3">
                              <Icon className="h-5 w-5 flex-shrink-0 mt-0.5" />
                              <div className="flex-1">
                                <div className="flex items-center justify-between mb-1">
                                  <span className="text-xs font-medium uppercase">{reminder.type.replace('_', ' ')}</span>
                                  <div className="flex items-center gap-2">
                                    {!reminder.isRead && (
                                      <span className="px-2 py-0.5 bg-red-500 text-white text-xs rounded-full">New</span>
                                    )}
                                    {reminder.expiresAt && new Date(reminder.expiresAt) < new Date() && (
                                      <span className="px-2 py-0.5 bg-gray-500 text-white text-xs rounded-full">Expired</span>
                                    )}
                                  </div>
                                </div>
                                <p className="text-sm font-medium mb-1 break-words" style={{ wordWrap: 'break-word', overflowWrap: 'break-word' }}>{reminder.message}</p>
                                {reminder.action && (
                                  <p className="text-xs opacity-75 mt-1">Action: {reminder.action}</p>
                                )}
                                {reminder.expiresAt && (
                                  <p className="text-xs opacity-75 mt-1">
                                    Expires: {new Date(reminder.expiresAt).toLocaleDateString()}
                                  </p>
                                )}
                                <p className="text-xs opacity-50 mt-2">
                                  {new Date(reminder.createdAt).toLocaleString()}
                                </p>
                              </div>
                            </div>
                          </div>
                        );
                      })
                    ) : (
                      <div className="text-center py-8">
                        <Bell className="h-12 w-12 text-gray-300 mx-auto mb-3" />
                        <p className="text-gray-500">
                          {reminderData.items.length === 0 
                            ? "No reminders yet" 
                            : "No reminders match the selected filters"}
                        </p>
                      </div>
                    )}
                  </div>
                </div>
              </div>

              {/* Goals Section */}
              <div className="bg-white rounded-lg border border-gray-200 shadow-sm p-6">
                <div className="flex items-center gap-2 mb-4">
                  <Target className="h-5 w-5 text-emerald-600" />
                  <h3 className="text-lg font-semibold text-gray-900">Driver Goals & Tracking</h3>
                </div>
                <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                  <div className="p-4 bg-blue-50 rounded-lg border border-blue-200">
                    <div className="flex items-center gap-2 mb-2">
                      <Target className="h-4 w-4 text-blue-600" />
                      <span className="text-sm font-medium text-gray-700">Trips Goal</span>
                    </div>
                    <p className="text-2xl font-bold text-blue-600">-</p>
                    <p className="text-xs text-gray-500 mt-1">Set reminder goal for trips</p>
                  </div>
                  <div className="p-4 bg-purple-50 rounded-lg border border-purple-200">
                    <div className="flex items-center gap-2 mb-2">
                      <Target className="h-4 w-4 text-purple-600" />
                      <span className="text-sm font-medium text-gray-700">Earnings Goal</span>
                    </div>
                    <p className="text-2xl font-bold text-purple-600">-</p>
                    <p className="text-xs text-gray-500 mt-1">Set reminder goal for earnings</p>
                  </div>
                </div>
                <p className="text-xs text-gray-500 mt-4">
                  Goals can be set when creating reminders to track driver progress
                </p>
              </div>
            </div>
          ) : (
            <div className="bg-white rounded-lg border border-gray-200 shadow-sm p-12 text-center">
              <Bell className="h-12 w-12 text-gray-400 mx-auto mb-4" />
              <p className="text-gray-500">Select a driver to view their reminders</p>
            </div>
          )}
        </div>
      </div>

      {/* Create Reminder Modal */}
      {showCreateModal && selectedDriver && (
        <div className="fixed inset-0 bg-black bg-opacity-50 flex items-center justify-center z-50 p-4" style={{ boxSizing: 'border-box' }}>
          <div className="bg-white rounded-xl p-6 w-full max-w-2xl max-h-[90vh] overflow-y-auto" style={{ boxSizing: 'border-box', width: '100%', maxWidth: '672px' }}>
            <div className="flex items-center justify-between mb-6">
              <h2 className="text-xl font-bold text-gray-900">Create Reminder</h2>
              <button
                onClick={() => setShowCreateModal(false)}
                className="p-2 hover:bg-gray-100 rounded-lg transition-colors flex-shrink-0"
              >
                <X className="h-5 w-5" />
              </button>
            </div>

            <div className="space-y-4" style={{ boxSizing: 'border-box', width: '100%' }}>
              <div style={{ boxSizing: 'border-box', width: '100%' }}>
                <label className="block text-sm font-medium text-gray-700 mb-2">Reminder Type</label>
                <div className="grid grid-cols-2 md:grid-cols-3 gap-2" style={{ boxSizing: 'border-box', width: '100%' }}>
                  {REMINDER_TYPES.map((type) => {
                    const Icon = type.icon;
                    return (
                      <button
                        key={type.value}
                        onClick={() => setReminderType(type.value)}
                        className={`p-3 rounded-lg border-2 transition-all text-left w-full ${
                          reminderType === type.value
                            ? "border-emerald-600 bg-emerald-50"
                            : "border-gray-200 hover:border-gray-300"
                        }`}
                        style={{ boxSizing: 'border-box', minWidth: 0 }}
                      >
                        <div className="flex items-center gap-2 mb-1">
                          <Icon className={`h-4 w-4 flex-shrink-0 ${reminderType === type.value ? "text-emerald-600" : "text-gray-600"}`} />
                          <span className={`text-sm font-medium truncate ${reminderType === type.value ? "text-emerald-700" : "text-gray-700"}`}>
                            {type.label}
                          </span>
                        </div>
                        <p className="text-xs text-gray-500 line-clamp-2">{type.description}</p>
                      </button>
                    );
                  })}
                </div>
              </div>

              <div style={{ boxSizing: 'border-box', width: '100%' }}>
                <label className="block text-sm font-medium text-gray-700 mb-2">Message *</label>
                <textarea
                  value={reminderMessage}
                  onChange={(e) => setReminderMessage(e.target.value)}
                  placeholder="Enter reminder message..."
                  rows={4}
                  className="w-full px-4 py-2 border-2 border-gray-300 rounded-lg focus:outline-none focus:border-emerald-500 resize-none"
                  style={{ boxSizing: 'border-box', width: '100%' }}
                  required
                />
              </div>

              <div className="grid grid-cols-1 md:grid-cols-2 gap-4" style={{ boxSizing: 'border-box', width: '100%' }}>
                <div style={{ boxSizing: 'border-box', width: '100%', minWidth: 0 }}>
                  <label className="block text-sm font-medium text-gray-700 mb-2">Action (Optional)</label>
                  <input
                    type="text"
                    value={reminderAction}
                    onChange={(e) => setReminderAction(e.target.value)}
                    placeholder="e.g., Renew License"
                    className="w-full px-4 py-2 border-2 border-gray-300 rounded-lg focus:outline-none focus:border-emerald-500"
                    style={{ boxSizing: 'border-box', width: '100%' }}
                  />
                </div>
                <div style={{ boxSizing: 'border-box', width: '100%', minWidth: 0 }}>
                  <label className="block text-sm font-medium text-gray-700 mb-2">Action Link (Optional)</label>
                  <input
                    type="text"
                    value={reminderActionLink}
                    onChange={(e) => setReminderActionLink(e.target.value)}
                    placeholder="e.g., /driver/documents"
                    className="w-full px-4 py-2 border-2 border-gray-300 rounded-lg focus:outline-none focus:border-emerald-500"
                    style={{ boxSizing: 'border-box', width: '100%' }}
                  />
                </div>
              </div>

              <div className="grid grid-cols-1 md:grid-cols-2 gap-4" style={{ boxSizing: 'border-box', width: '100%' }}>
                <div style={{ boxSizing: 'border-box', width: '100%', minWidth: 0 }}>
                  <label className="block text-sm font-medium text-gray-700 mb-2">Expiration Date (Optional)</label>
                  <input
                    type="date"
                    value={reminderExpiresAt}
                    onChange={(e) => setReminderExpiresAt(e.target.value)}
                    className="w-full px-4 py-2 border-2 border-gray-300 rounded-lg focus:outline-none focus:border-emerald-500"
                    style={{ boxSizing: 'border-box', width: '100%' }}
                  />
                </div>
                <div style={{ boxSizing: 'border-box', width: '100%', minWidth: 0 }}>
                  <label className="block text-sm font-medium text-gray-700 mb-2">Goal/Tracking (Optional)</label>
                  <input
                    type="text"
                    value={reminderGoal}
                    onChange={(e) => setReminderGoal(e.target.value)}
                    placeholder="e.g., Complete 50 trips this month"
                    className="w-full px-4 py-2 border-2 border-gray-300 rounded-lg focus:outline-none focus:border-emerald-500"
                    style={{ boxSizing: 'border-box', width: '100%' }}
                  />
                </div>
              </div>

              <div className="flex gap-3 pt-4" style={{ boxSizing: 'border-box', width: '100%' }}>
                <button
                  onClick={createReminder}
                  disabled={!reminderMessage.trim() || creating}
                  className="flex-1 px-4 py-2 bg-emerald-600 text-white rounded-lg hover:bg-emerald-700 transition-all disabled:opacity-50 disabled:cursor-not-allowed"
                  style={{ boxSizing: 'border-box', minWidth: 0 }}
                >
                  {creating ? "Creating..." : "Create Reminder"}
                </button>
                <button
                  onClick={() => setShowCreateModal(false)}
                  className="px-4 py-2 bg-gray-200 text-gray-700 rounded-lg hover:bg-gray-300 transition-all flex-shrink-0"
                  style={{ boxSizing: 'border-box' }}
                >
                  Cancel
                </button>
              </div>
            </div>
          </div>
        </div>
      )}
    </div>
  );
}
