SELECT COLUMN_NAME, DATA_TYPE, IS_NULLABLE
FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_SCHEMA = DATABASE()
  AND LOWER(TABLE_NAME) = 'groupbooking'
  AND COLUMN_NAME IN ('minHotelStar', 'minHotelStarLabel');
